language: java
services:
  - docker

build:
  - docker build -t registry.heroku.com/${APP_NAME} .
  - docker ps -a
  - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
  - docker push registry.heroku.com/${APP_NAME}